apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
stringData:
  # We use 'stringData' so you can paste plain text here.
  # Kubernetes will convert it to base64 automatically.
  mongo-uri: "mongodb://mongodb-service:27017/mern-admin"
  jwt-secret: "thiscanbechangedlater123654789"
