apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
stringData:
  # The mongo-uri must use the service name defined in 02-mongodb-svc.yaml
  mongo-uri: "mongodb://mongodb-service:27017/mern-admin"
  jwt-secret: "thiscanbechangedlater123654789"