apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
stringData:
  mongo-uri: {{ .Values.backend.secrets.databaseUri | quote }}
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | quote }}
  secret: {{ .Values.backend.secrets.secret | quote }}
  key: {{ .Values.backend.secrets.key | quote }}
